name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.8.0"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install

      - name: Check for version change
        id: version-check
        run: |
          git fetch --tags
          LAST_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Last published version: $LAST_VERSION"
          echo "Current version: $CURRENT_VERSION"

          if [ "$CURRENT_VERSION" == "$LAST_VERSION" ]; then
            echo "No new version to publish."
            exit 0
          fi

      - name: Publish package
        run: |
          npm version patch  # or minor/major based on your preference
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
